### ISSUE TITLE
Adding links on runtime 

### ISSUE THREAD

**Issue by killgt** [vmitchell85/nova-links#1]
I think it would be more useful to add links at component constructor or on a method, to allow better customization. Currently there is no way to change the links based on the user.

**Comment by vmitchell85** [comment]
Thanks for your suggestion!

I though about allowing the user to add links from a page, but it seemed a bit much to store in the DB, or generate a file to store them.

My use case was to provide a way to link back to specific pages on the frontend of my app.

It wouldn't be hard to allow two options. Would you prefer a DB table and a per-user link list?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by killgt** [comment]
I think both options maybe are a overkill, the user can build that feature if this package uses a builder pattern, it will look like:
```php 
public function tools()
{
    return [
        // ...
        (new \vmitchell85\NovaLinks\Links())
               ->addLink('Tailwind docs', 'https://tailwindcss.com/'),
               ->addLink('Laravel docs', 'https://laravel.com/docs/5.5/'),
    ];
}
```

**Comment by vmitchell85** [comment]
Not a bad way to go... Definitely a good option... I originally avoided it in the case where the user has a lot of links. It could clutter up the service provider. But as I think about it more people probably won't put more than a few links.

Thanks again for the feedback... I think I'll refactor to this design soon, or if you want to submit a PR I'd accept it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by levi-beers** [comment]
Wanted to chime in. First, thank you for writing this. I'm new to Laravel & I was struggling to figure out how add links on Nova. Poking around your source helped me understand those things. I tend to agree with @killgt on both methods being overkill. But I do like the builder pattern, that would be very effective.
